name: Hangouts Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: manatechdev/todo:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set permissions for private key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Pull Docker image
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@18.223.62.149 'sudo docker pull manatechdev/hangouts:latest'
      - name: Stop running container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@18.223.62.149 'sudo docker stop hangouts || true'
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@18.223.62.149 'sudo docker rm hangouts || true'
      - name: Run new container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@18.223.62.149 'sudo docker run -d --name hangouts --network manaflow -e VIRTUAL_HOST="hangouts.manatech.dev" manatechdev/hangouts:latest'
